vsphere_datacenter      = "tmi-w01-dc01"
vsphere_compute_cluster = "tmi-w01-cl01-dev"
vsphere_resource_pool   = "tmi-w01-dc01/tmi-w01-cl01-dev/Resources"
vsphere_datastore       = "troy-nonprod-ds-vsan"
vsphere_network         = "tmi-w01-cl01-dev-vds02-pg-app-221"
vsphere_folder          = "dev/coa-search"
vsphere_template        = "linux-ubuntu-server-20-04-lts-tmi-w01-cl01-dev"
