vsphere_datacenter      = "REPLACEME_datacenter_REPLACEME"
vsphere_compute_cluster = "REPLACEME_compute_cluster_REPLACEME"
vsphere_resource_pool   = "REPLACEME_resource_pool_REPLACEME"
vsphere_datastore       = "REPLACEME_datastore_REPLACEME"
vsphere_network         = "REPLACEME_network_REPLACEME"
vsphere_folder          = "REPLACEME_env_REPLACEME/REPLACEME_cluster_name_REPLACEME"
vsphere_template        = "REPLACEME_template_name_REPLACEME"
