---
- name: Install netmgmt
  command: /usr/bin/tdnf -y install netmgmt
  args:
    creates: /usr/bin/netmgr
  when: ansible_facts['os_family'] == "VMware Photon OS"

- name: Set Hostname (PhotonOS)
  command: netmgr hostname --set --name "{{ hostname }}"
  when: ansible_facts['os_family'] == "VMware Photon OS"

- name: Set Hostname (Non-PhotonOS)
  command: hostname "{{ hostname }}"
  when: ansible_facts['os_family'] != "VMware Photon OS"

- name: Set /etc/hostname (Non-PhotonOS)
  command: hostnamectl set-hostname '"{{ hostname }}"'
  when: ansible_facts['os_family'] != "VMware Photon OS"
