vsphere_datacenter      = "tmi-w01-dc01"
vsphere_compute_cluster = "tmi-w01-cl01-dev"
vsphere_resource_pool   = "tmi-w01-dc01/tmi-w01-cl01-dev/Resources"
vsphere_datastore       = "troy-nonprod-ds-vsan"
vsphere_network         = "tmi-w01-cl01-vds01-pg-streaminga-206"
vsphere_folder          = "non-prod/Feature/streaming"
vsphere_template        = "linux-ubuntu-server-20-04-lts"
