vsphere_datacenter      = "dal-w01-dc01"
vsphere_compute_cluster = "dal-w01-cl01"
vsphere_resource_pool   = "dal-w01-dc01/dal-w01-cl01/Resources"
vsphere_datastore       = "dal-w01-cl01-ds-vsan01"
vsphere_network         = "dal-w01-cl01-vds01-pg-ops-203"
vsphere_folder          = "Infrastructure/photon-cluster"
vsphere_template        = "linux-photon-server-4"